import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const SuisseIntlRegular = localFont({
  src: "../../public/fonts/SuisseIntlRegular.otf",
  variable: "--SuisseIntlRegular",
  display: "swap",
});

const SuisseIntlMedium = localFont({
  src: "../../public/fonts/SuisseIntlMedium.woff2",
  variable: "--SuisseIntlMedium",
  display: "swap",
});

const SuisseIntlCondBold = localFont({
  src: "../../public/fonts/SuisseIntlCondBold.woff2",
  variable: "--SuisseIntlCondBold",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${SuisseIntlCondBold.variable} ${SuisseIntlMedium.variable} ${SuisseIntlRegular.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
